#!/bin/csh

# $Log: kl2sd,v $
# Revision 1.2  1998/07/17 00:13:40  krishna
# Things that make you go hmmmm.
#
# Revision 1.1  1998/06/06 22:44:48  krishna
# Initial revision
#

if (($#argv < 1) || ("$1" == "-h")) then
   echo "Usage: kl2sd file1.wav file2.wav ..."
   exit
endif

foreach f ($*)
   set rt = $f:r  # Get basename

   set samplingFreq = `klinfo -f $f`	# Get sampling rate
   kl2raw $rt $rt.raw.tmp		# Get just binary data

   # Convert from binary data to ESPS .sd file

   btosps -f $samplingFreq -c "kl2sd conversion" $rt.raw.tmp $rt.fsd
   featosd $rt.fsd $rt.sd
   rm $rt.raw.tmp $rt.fsd
end

