.TH MAC2KL 1 "XKL Utilities (March 1, 1999)" "MIT Speech Group" \" -*- nroff -*-
.SH NAME
mac2kl \- convert a MacIntosh (.aiff) audio file to a Klatt (.wav) audio file
.SH SYNOPSIS
.B mac2kl [-h | --help] <infile> <outfile>
.SH DESCRIPTION
.PP
.B mac2kl
convert a MacIntosh (.aiff) audio file, infile, to a Klatt (.wav) audio
file, outfile.

With no arguments, the program prints out the usage message.

.SS OPTIONS
.TP
.I "\-\-help or \-h"
Print a usage message.

.SH EXAMPLES
kl2mac quiet.aiff quiet.wav

.SH AUTHOR
Send bugs or comments to xkldev@speech.mit.edu.

.SH SEE ALSO
.BR concat (1),
.BR klinfo (1),
.BR klgain (1),
.BR klplay (1),
.BR klrecord (1),
.BR kl2raw (1),
.BR raw2kl (1),
.BR kl2sd (1),
.BR sd2kl (1),
.BR kl2mac (1),
.BR kl2ms (1),
.BR ms2kl (1),
.BR kl2mat (1),
.BR mat2kl (1)

